language: python
sudo: required
python:
  - "3.6"
services:
  - docker
install:
 - sudo apt-get install -y curl
 - sudo pip install -U pip
 - sudo curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
 - sudo chmod +x /usr/local/bin/docker-compose
 - docker-compose --version
 - pip install -r dev-requirements.txt
script:
 - mypy --ignore-missing-imports .
 - flake8 activitypub.py
 - cp -r tests/fixtures/me.yml config/me.yml
 - docker-compose up -d
 - docker-compose ps
 - WEB_PORT=5006 CONFIG_DIR=./tests/fixtures/instance1/config docker-compose -p instance1 -f docker-compose-tests.yml up -d
 - docker-compose -p instance1 -f docker-compose-tests.yml ps
 - docker inspect instance1_web_1
 - WEB_PORT=5007 CONFIG_DIR=./tests/fixtures/instance2/config docker-compose -p instance2 -f docker-compose-tests.yml up -d
 - docker-compose -p instance2 -f docker-compose-tests.yml ps
 # Integration tests first
 - python -m pytest -v --ignore data -k integration
 # Federation tests (with two local instances)
 - pwd
 - ls -lR .
 - python -m pytest -v -s --ignore data -k federation
 - docker logs instance1_web_1
