version: '2'
services:
  web:
    image: 'microblogpub:latest'
    ports:
     - "${WEB_PORT}:5005"
    links:
     - mongo
     - rmq
     - poussetaches
    volumes:
     - "${CONFIG_DIR}:/app/config"
     - "./static:/app/static"
    environment:
     - MICROBLOGPUB_AMQP_BROKER=pyamqp://guest@rmq//
     - MICROBLOGPUB_MONGODB_HOST=mongo:27017
     - POUSSETACHES_AUTH_KEY=123
  celery:
    image: 'microblogpub:latest'
    links:
     - mongo
     - rmq
    command: 'celery worker -l info -A tasks'
    volumes:
     - "${CONFIG_DIR}:/app/config"
    environment:
     - MICROBLOGPUB_AMQP_BROKER=pyamqp://guest@rmq//
     - MICROBLOGPUB_MONGODB_HOST=mongo:27017
  mongo:
    image: "mongo:latest"
    volumes:
     - "${DATA_DIR}/mongodb:/data/db"
  rmq:
    image: "rabbitmq:latest"
    hostname: "my-rabbit"
    environment:
     - RABBITMQ_ERLANG_COOKIE=secretrabbit
     - RABBITMQ_NODENAME=rabbit@my-rabbit
    volumes:
     - "${DATA_DIR}/rabbitmq:/var/lib/rabbitmq"
  poussetaches:
    image: "poussetaches:latest"
    ports:
     - '7991'
    environment:
     - POUSSETACHES_AUTH_KEY=123
