version: '3'
services:
  web:
    build: .
    ports:
     - "${WEB_PORT}:5005"
    links:
     - mongo
     - rabbitmq
    volumes:
     - "${CONFIG_DIR}:/app/config"
     - "./static:/app/static"
    environment:
     - MICROBLOGPUB_AMQP_BROKER=pyamqp://guest@rabbitmq//
     - MICROBLOGPUB_MONGODB_HOST=mongo:27017
  celery:
    build: .
    links:
     - mongo
     - rabbitmq
    command: 'celery worker -l info -A tasks'
    environment:
     - MICROBLOGPUB_AMQP_BROKER=pyamqp://guest@rabbitmq//
     - MICROBLOGPUB_MONGODB_HOST=mongo:27017
  mongo:
    image: "mongo:latest"
    volumes:
     - "${DATA_DIR}:/data/db"
  rabbitmq:
    image: "rabbitmq:latest"
