version: '3.5'
services:
  web:
    build: .
    ports:
     - "${WEB_PORT}:5005"
    links:
     - mongo
     - rmq
    volumes:
     - "${CONFIG_DIR}:/app/config"
     - "./static:/app/static"
    environment:
     - MICROBLOGPUB_AMQP_BROKER=pyamqp://guest@rmq//
     - MICROBLOGPUB_MONGODB_HOST=mongo:27017
     - MICROBLOGPUB_DEBUG=1
  celery:
#    image: "instance1_web"
    build: .
    links:
     - mongo
     - rmq
    command: 'celery worker -l info -A tasks'
    volumes:
     - "${CONFIG_DIR}:/app/config"
    environment:
     - MICROBLOGPUB_AMQP_BROKER=pyamqp://guest@rmq//
     - MICROBLOGPUB_MONGODB_HOST=mongo:27017
  mongo:
    image: "mongo:latest"
  rmq:
    image: "rabbitmq:latest"
    hostname: "my-rabbit"
    environment:
     - RABBITMQ_ERLANG_COOKIE=secretrabbit
     - RABBITMQ_NODENAME=rabbit@my-rabbit
networks:
  default:
    name: microblogpubfede 
