version: '3.5'
services:
  web:
    image: 'microblogpub:latest'
    ports:
     - "${WEB_PORT}:5005"
    volumes:
     - "${CONFIG_DIR}:/app/config"
     - "./static:/app/static"
    environment:
     - MICROBLOGPUB_AMQP_BROKER=pyamqp://guest@rmq//
     - MICROBLOGPUB_MONGODB_HOST=${COMPOSE_PROJECT_NAME}_mongo_1:27017
     - MICROBLOGPUB_DEBUG=1
     - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
     - POUSSETACHES_AUTH_KEY=123
  celery:
#    image: "instance1_web"
    image: 'microblogpub:latest'
    command: 'celery worker -l info -A tasks'
    volumes:
     - "${CONFIG_DIR}:/app/config"
    environment:
     - MICROBLOGPUB_AMQP_BROKER=pyamqp://guest@rmq//
     - MICROBLOGPUB_MONGODB_HOST=mongo:27017
     - MICROBLOGPUB_DEBUG=1
  mongo:
    image: "mongo:latest"
  rmq:
    image: "rabbitmq:latest"
    hostname: "my-rabbit"
    environment:
     - RABBITMQ_ERLANG_COOKIE=secretrabbit
     - RABBITMQ_NODENAME=rabbit@my-rabbit
  poussetaches:
    image: "poussetaches:latest"
    ports:
     - '7991'
    environment:
     - POUSSETACHES_AUTH_KEY=123
networks:
  default:
    name: microblogpubfede 
